# Generated by Django 5.2.4 on 2026-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_usage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
