# Generated by Django 5.2.4 on 2026-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_usage", "0002_vehicleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentry",
            name="entry_type",
            field=models.CharField(
                choices=[("entry", "Entry"), ("exit", "Exit")],
                default="entry",
                max_length=10,
            ),
        ),
    ]
