# Generated by Django 5.2.4 on 2026-03-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_usage", "0003_vehicleentry_entry_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupancySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupied", models.IntegerField(default=0)),
                ("vacant", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.RemoveField(
            model_name="slotstatuslog",
            name="slot",
        ),
        migrations.DeleteModel(
            name="VehicleEntry",
        ),
        migrations.DeleteModel(
            name="ParkingSlot",
        ),
        migrations.DeleteModel(
            name="SlotStatusLog",
        ),
    ]
