# Generated by Django 5.2.4 on 2026-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="snapshot_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
