# Generated by Django 5.2.4 on 2026-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_camera_snapshot_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="stream_url",
            field=models.CharField(
                blank=True, default="/stream/stream.m3u8", max_length=500
            ),
        ),
    ]
