# Generated by Django 5.2.4 on 2026-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicles/"),
        ),
    ]
