# Generated by Django 5.2.4 on 2025-08-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('FW', 'Four-wheels'), ('TW', 'Two-wheels')], max_length=2)),
                ('plate_number', models.CharField(max_length=100)),
                ('gate_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.driverprofile')),
            ],
        ),
    ]
