# Generated by Django 5.2.4 on 2025-08-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barangay',
            table='refbrgy',
        ),
    ]
