# Generated by Django 5.2.4 on 2026-02-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_vehicle_vehicle_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="barangay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.barangay",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
