# Generated by Django 5.2.4 on 2025-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_barangay_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
