[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = ["pip3 install -r requirements.txt && python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn parktrack.wsgi --workers 2 --timeout 120"